Issue/14
commonprofiles-care/fhir pull request #35
Opened 2022-11-14 16:16 UTC by peturv

ServiceRequestSelfReferralSEVendorLite profile converted from ServiceRequestSelfReferralSEVendorLite.xml to ServiceRequestSelfReferralSEVendorLite.fsh

2022-11-15 08:27 UTC, vjernelov approved these changes
Not sure I have the background needed to review this from a content point-of-view.

As far as I can tell it looks ok though.

2022-11-24 13:02 UTC, RebeckaHansson requested changes
I found some missing profiling to a few attributes. I suspect these could have been done in a core profile from the first place:
basedOn, replaces and requisition should be ..0
intent should have order as fixed value
doNotPerform should be ..0
quantity should be ..0
encounter should be ..0, comment: Not applicable for self-referral as there has never been an encounter before the self-referral as it is the start of the process.
asNeeded should be ..0, comment: Not applicable for self-referral
specimen should be ..0
instruction should be ..0, comment: Not applicable for self-referral

2022-12-09 10:13 UTC, niclas86 commented
Please have a look at the updates made by @peturv @RebeckaHansson

2023-01-05 09:42 UTC, RebeckaHansson approved these changes

2023-01-20 10:21 UTC, merged